project:
  type: website
  output-dir: docs

website:
  title: "Adam Koplik"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Feed"
        file: feed.qmd
  page-footer: "© 2026 Adam Koplik"

format:
  html:
    theme:
      light: flatly
      dark: cosmo
    toggle: true
    include-in-header: _includes/site.html
    css: styles.css
    highlight-style: dracula
    anchor-sections: true

resources:
  - projects/**
