# What an Idiot: On the 2026 New York Knicks and Learning How to Believe Again
As OG Anunoby tossed the championship-clinching ball into the crowd, 23 years of fandom came pouring out of me. I screamed a noise I don’t think I can ever replicate — as a lifetime of pessimism and sorrow were exorcised from my body at once. The tears started then and they’ve been tough to stop ever since. I hugged every person I could find, crying with strangers who understood exactly what I was going through, trying to make this moment last forever. But as I woke up the next morning, overcome with a sense of calm and peace that is rare to feel nowadays, I realized there’s nothing more I have to do: this win will be with me for the rest of my life.

I was born in 2003. From the day I was born until I was a sophomore in college, the Knicks won one singular playoff series. That didn’t stop me from talking my family’s ears off about how every single draft pick, every single free agent signing, and every single trade they made was the move that would turn the franchise around. After the euphoria of Linsanity followed by the red-hot start by the 2012–13 Knicks, I was certain this was the team. The Landry Fields (shoutout) days were over, and I was going to be a fan of a perennial winner led by Carmelo Anthony, Jason Kidd, Tyson Chandler, JR Smith, and Steve Novak (I did not have a very strong understanding of “ages” at this moment. After the Roy Hibbert led Pacers beat us in six and tears streamed down by 10-year-old face, I was sure we were going to be back. I was wrong. I was wrong when I thought Andrea Bargnani was the missing piece. I was wrong when I thought Kristaps Porzingis was going to win MVP after MVP. I was wrong when I thought Derrick Rose-Joakim Noah-Courtney Lee was the offseason haul of the century. I was wrong about Frank Ntilikina, about Kevin Knox, about Allonzo Trier, about Cleanthony Early, about Phil Jackson, about David Fizdale, and on, and on, and on…

Join The Writer's Circle event
Every year I would have hope, and every year I would sit with my head in my hands wondering why my father transferred his curse of sports fandom onto me. Kevin Durant didn’t want to come here. Kyrie Irving didn’t want to come here. We missed out on Zion Williamson. I was wrong so much that it was easier to just expect the worst. I refused to let myself hope because the hope allows for the hurt. Any move the Knicks make will fail, because they are the Knicks. It wasn’t “next year is our year”, but “we will never be good”.

Press enter or click to view image in full size

Photo via Getty Images
Even as the Knicks started winning again, I wouldn’t allow myself to buy in. Until last year, when the team had back-to-back 20+ point comebacks against the Celtics in the second round and, for one day, I allowed myself to believe they could do it. They could be winners. I could be a winner. Of course, that all came crashing back to reality when they choked away Game 1 of the Eastern Conference Finals in an all-time crushing loss. I kicked myself for allowing belief to creep back in. What an idiot. This is the Knicks. We don’t win. Things don’t get better.

As I bask in the glory of a championship that will last a lifetime, I look back on my younger self (two months ago) and I once again think “what an idiot”. This whole ride has slowly fixed my ability to hope. They’ve exorcised the demons of a lifetime of sports sadness. The Knicks were down by double digits seven times this playoff run. They won six of those games, including two improbable 20+ point comebacks. They proved every single game that it didn’t matter the situation: they would fight back. And now, the Knicks are world champions. They didn’t get lucky. They didn’t win a lottery or sign the savior in free agency (at least according to every NBA analyst, I love you Jalen Brunson). They built a team of guys who play for each other, guys who work their asses off, and guys who believe that when the buzzer sounds on any given night, they will have the higher score. It doesn’t matter if they’re down 20. It doesn’t matter if their best player is a foot-and-a-half shorter than his foe. It doesn’t matter if you didn’t believe. Belief. Heart. Resilience.

The Knicks felt like a symbol of everything broken in the world: Climate change. Politics. Hatred. War. And I just had to watch, hopeless and powerless, expecting the worst. Yes, a basketball team was my embodiment of the world’s evils. No, I am not (and have never claimed to be) a mentally healthy human being.

This Knicks team didn’t believe that things couldn’t get better. Whether it was the franchise’s failures, the season’s struggles, or a single game’s deficit, they always felt in their core that they would win. One possession at a time. No matter how bad things get, we can always make a difference. Whether it’s the world, a community, or one person. Keep pushing. One possession at a time.

There’s a world out there that we can live in — that we deserve to live in. A world of community and love and hope that, even with all the negativity that has come before, tomorrow can still be a better day. A world full of belief, of heart, and of resilience. And, most importantly, a world where the New York Knicks can be NBA champions. That world is here.
